version: '3.8'

services:
  azure-sql-edge:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      SA_PASSWORD: "ergo.1234"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
  promo-code-api:
    image: promo-code-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "443:443"
    environment:
      DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: false
    depends_on:
      - azure-sql-edge
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  redis-data:
